# Top‐level timeout set to 14400 seconds (4 hours)
timeout: "28800s"

options:
  logging: CLOUD_LOGGING_ONLY

  # Pick a larger machine type than the default.
  # Available built‐in options: E2_SMALL, E2_MEDIUM (default), E2_HIGHCPU_8, E2_HIGHCPU_32
  machineType: "E2_HIGHCPU_32"

steps:
  # STEP 2: SonarScanner Analysis Step
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /tmp/.sonar
        mkdir -p /tmp/.scannerwork
        export SONAR_USER_HOME=/tmp/.sonar
        sonar-scanner \
          -Dsonar.projectKey=vscode-sonar-3m-cloudbuild \
          -Dsonar.projectName=vscode-sonar-3m-cloudbuild \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonar-demo-pt.iexperts.cloud \
          -Dsonar.login=sqp_e353036cad6b27e0f64b440c6035e27ce77d1b82 \
          -Dsonar.log.level=DEBUG \
          -Dsonar.working.directory=/tmp/.scannerwork
